MovieManagementSystem/MovieManagement/moviemanagement/moviemanagement/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore
from django.conf import settings # type: ignore
from django.conf.urls.static import static # type: ignore
# from movies.views import CustomCsrfFailureView # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include("movies.urls", namespace='movies')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MovieManagementSystem/MovieManagement/moviemanagement/movies/urls.py
from django.urls import path # type: ignore
from . import views

app_name = "movies"

urlpatterns = [
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('signin/', views.SigninView.as_view(), name='signin'),
    path('signout/', views.SignoutView.as_view(), name='signout'),

    path('homepage/', views.HomePageView.as_view(), name='home'),

    path('moviepage/', views.MoviePageView.as_view(), name='movie'),
    path('addmoviepage/', views.AddEditMovieView.as_view(), name='addmovie'),
    path('editmoviepage/<int:movie_id>/', views.AddEditMovieView.as_view(), name='editmovie'), ##
    path('deletemovie/<int:pk>/', views.DeleteMovie.as_view(), name='deletemovie'),
    path('movieDetailpage/<int:movie_id>/', views.MovieDetailView.as_view(), name='movieDetail'),

    path('movie/manage_cast_language/<int:movie_id>/', views.ManageCastLanguagesView.as_view(), name='manage_cast_language'),
    path('removecast/<int:pk>/', views.RemoveCast.as_view(), name='removeCast'),
    path('removelanguage/<int:pk>/', views.RemoveLanguage.as_view(), name='removeLanguage'),
    
    path('genrepage/', views.GenrePageView.as_view(), name='genre'),
    path('addgenrepage/', views.AddEditGenreView.as_view(), name='addgenre'),
    path('editgenre/<int:genre_id>/', views.AddEditGenreView.as_view(), name='editgenre'),
    path('deletegenre/<int:pk>/', views.DeleteGenre.as_view(), name='deletegenre'),

    
    path('peoplepage/', views.PersonListView.as_view(), name='people'),
    path('addpeoplepage/', views.AddEditPeopleView.as_view(), name='addpeople'),
    path('editpeoplepage/<int:person_id>/', views.AddEditPeopleView.as_view(), name='editpeople'), ##
    path('deletepeople/<int:pk>/', views.DeletePeople.as_view(), name='deletepeople'),
    path('personDetailpage/<int:person_id>/', views.PersonDetailView.as_view(), name='personDetail'),

    path('addreviewpage/<int:movie_id>/', views.AddEditReview.as_view(), name='addreview'),
    path('editreviewpage/<int:movie_id>/<int:review_id>/', views.AddEditReview.as_view(), name='editreview'),
    path('deletereview/<int:pk>/', views.DeleteReview.as_view(), name='deletereview'),
]

MovieManagementSystem/MovieManagement/moviemanagement/movies/models.py
from django.db import models # type: ignore
from django.db.models import Q # type: ignore
from django.core.validators import MaxValueValidator, MinValueValidator # type: ignore
from django.contrib.auth.models import AbstractUser # type: ignore

class Users(AbstractUser):
    class RoleChoice(models.TextChoices):
        USER = 'user', 'RegularUser'
        ADMIN = 'admin', 'SiteAdministrator'
    
    user_role = models.CharField(
        max_length=15,
        choices=RoleChoice.choices,
        default=RoleChoice.USER, 
    )

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        
    # @property
    # def is_admin(self):
    #     return self.user_role == self.RoleChoice.ADMIN
    
    # @property
    # def is_regular_user(self):
    #     return self.user_role == self.RoleChoice.USER
    
class Genre(models.Model):
    genre_name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.genre_name

class Person(models.Model):
    class Role(models.TextChoices):
        ACTOR = 'actor', 'Actor'
        DIRECTOR = 'director', 'Director'
        WRITER = 'writer', 'Writer'

    person_name = models.CharField(max_length=100)
    role_type = models.CharField(max_length=10, choices=Role.choices)
    bio = models.TextField(null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    profile_photo = models.ImageField(upload_to='posters/', blank=True, null=True)

    def __str__(self):
        return self.person_name

class Movie(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(default=None)
    release_year = models.PositiveIntegerField(null=True)
    duration = models.PositiveIntegerField()
    poster = models.ImageField(upload_to='posters/', null=True, blank=True)
    rating = models.FloatField(default=0.0)
    genre = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True)
    director = models.ForeignKey(Person, on_delete=models.SET_NULL, null=True, limit_choices_to={'role_type': 'director'}, related_name='directed_movies')
    created_at = models.DateTimeField(auto_now_add=True)

    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='movies')

    def __str__(self):
        return f"{self.title} ({self.release_year})"


class MovieCast(models.Model):
    movie_name = models.ForeignKey(Movie, on_delete=models.CASCADE)
    person = models.ForeignKey(Person, on_delete=models.CASCADE, limit_choices_to={'role_type': 'actor'})
    character_name = models.CharField(max_length=100)


    class Meta:
        unique_together = (('movie_name', 'person'),)


class Language(models.Model):
    language = models.CharField(max_length=50, unique=True)
    # languages = ['English', 'Spanish', 'French', 'Filipino']

    def __str__(self):
        return self.language

class MovieLanguage(models.Model):
    movie_name = models.ForeignKey(Movie, on_delete=models.CASCADE)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.language}"

    class Meta:
        unique_together = (('movie_name', 'language'),)

class Review(models.Model):
    movie_name = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews')
    user_name = models.ForeignKey(Users, on_delete=models.CASCADE, null=True, blank=True)
    rating = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1, message='rating must be at least 1'), 
            MaxValueValidator(10, message='rating cannot exceed 10')
        ]
    )
    comment = models.TextField(default=None)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=Q(rating__range=(1, 10)),
                name='rating_in_range'
            ),
            models.UniqueConstraint(
                fields=['user_name', 'movie_name'], 
                name='unique_review'
            ),
        ]

MovieManagementSystem/MovieManagement/moviemanagement/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404 # type: ignore
from django.views import View # type: ignore
from django.views.generic import TemplateView, ListView, DeleteView, FormView, View # type: ignore
from django.views.decorators.csrf import csrf_protect # type: ignore
from django.utils.decorators import method_decorator # type: ignore
from django.views.decorators.cache import never_cache # type: ignore
from movies.models import Genre, Person, Movie, MovieCast, Language, MovieLanguage, Review
from datetime import date
from django.urls import reverse_lazy, reverse, resolve # type: ignore
from django.contrib import messages # type: ignore
from django.db.models import Avg # type: ignore 
from django.contrib.auth.views import LoginView, LogoutView # type: ignore
from django.views.generic.edit import FormView # type: ignore
from django.contrib.auth import login, logout, authenticate # type: ignore
from .form import RegistrationForm, SigninForm # type: ignore
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin # type: ignore
from .mixins import AdminRequiredMixin, UserAccessMixin, ReviewAuthorMixin
from .models import Users

# Home
class HomePageView(TemplateView):
    model = Movie
    template_name = 'movies/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        # filter on genre
        # context['movies'] = Movie.objects.all()
        selected_genre = self.request.GET.get('genres')
        if selected_genre:
            context['movies'] = Movie.objects.filter(genre__name=selected_genre)
        else:
            context['movies'] = Movie.objects.all()
        return context
    
    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search_query')
        genres_list = self.request.GET.getlist('genres')
        if search_query :
            queryset = queryset.filter(title_icontains=search_query)
        # if search_query:
        #     queryset = queryset.filter(person_name__icontains=search_query)
        if genres_list :
            queryset = queryset.filter(genre__in=genres_list)
        return queryset

# Movie
# class MoviePageView(LoginRequiredMixin, AdminRequiredMixin, ListView):
class MoviePageView(UserAccessMixin, ListView):
    model = Movie
    template_name = 'movies/movie.html'
    context_object_name = 'movies'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genres'] = Genre.objects.all()
        context['years'] = Movie.objects.values_list('release_year', flat=True).distinct().order_by('-release_year')

        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        print("movie list printing..")

        genres_list = self.request.GET.getlist('genres')
        print(f"genre: {genres_list}") ## 
        selected_year = self.request.GET.get('year')
        print(f"selected_year: {selected_year}") ##
        search_query = self.request.GET.get('search_movie')
        print(f"search_query: {search_query}") ## 

        if genres_list and 'all' not in [g.lower() for g in genres_list]:
            print("filter with genre block..")
            queryset = queryset.filter(genre__genre_name__in=genres_list)
        if selected_year and selected_year != "all":
            print("filter with year block..")
            queryset = queryset.filter(release_year=selected_year)
        if search_query:
            print("filter with search-query block..")
            queryset = queryset.filter(title__icontains=search_query)
        
        return queryset
        

@method_decorator(csrf_protect, name='dispatch')
class AddEditMovieView(View):
    template_name = 'movies/addmovie.html'

    def get(self, request, movie_id=None, *args, **kwargs):
        movie = None
        if movie_id:
            movie = get_object_or_404(Movie, id=movie_id)

        genres = Genre.objects.all()
        directors = Person.objects.filter(role_type=Person.Role.DIRECTOR)

        context = {
            'movie': movie,
            'genres': genres, 
            'directors': directors
        }
        return render(request, self.template_name, context)

    def post(self, request, movie_id=None, *args, **kwargs):
        print("Entering AddMovieView POST block")

        title = request.POST.get('title')
        description = request.POST.get('description')
        release_year = request.POST.get('release_year')
        duration = request.POST.get('duration')
        genre_name = request.POST.get('genre') or request.POST.get('genre_name')
        director_id = request.POST.get('director')
        uploaded_poster = request.FILES.get('poster') 

        print("FILES:", request.FILES)
        print("uploaded_poster:", uploaded_poster)
        
        if title:
            genre_obj = None
            if genre_name:
                # try:
                    if genre_name.isdigit():
                        genre_obj = Genre.objects.filter(id=int(genre_name)).first()
                    else:
                        genre_obj = Genre.objects.filter(genre_name__iexact=genre_name).first()
                # except Exception as e:
                #     print("Genre lookup error:", e)

            director_obj = None
            if director_id:
                # try:
                    if director_id.isdigit():
                        director_obj = Person.objects.filter(
                            id=int(director_id),
                            role_type=Person.Role.DIRECTOR
                        ).first()
                # except Exception as e:
                #     print("Director lookup error:", e)

            try:
                if movie_id:
                    movie = get_object_or_404(Movie, id=movie_id)
                    movie.title = title
                    movie.description = description or None
                    movie.release_year = int(release_year) if release_year and release_year.isdigit() else None
                    movie.duration = int(duration) if duration and duration.isdigit() else None
                    movie.genre = genre_obj
                    movie.director = director_obj

                    if uploaded_poster:
                        movie.poster = uploaded_poster

                    movie.save()
                    print(f"Updated movie: {movie}")

                else:
                    movie = Movie.objects.create(
                    title=title,
                    description=description or None,
                    release_year=int(release_year) if release_year and release_year.isdigit() else None,
                    duration=int(duration) if duration and duration.isdigit() else None,
                    genre=genre_obj,
                    director=director_obj,
                    poster=uploaded_poster
                )
                print(f"Created movie: {movie}")
                # redirect to manage cast/language after adding
                return redirect('movies:manage_cast_language', movie_id=movie.id)
            except Exception as e:
                print("Error creating movie:", e)

        genres = Genre.objects.all()
        directors = Person.objects.filter(role_type=Person.Role.DIRECTOR)
        context = {
            'movies': get_object_or_404(Movie, id=movie_id) if movie_id else None,
            'genres': genres, 
            'directors': directors
        }
        return render(request, self.template_name, context)

class DeleteMovie(LoginRequiredMixin, AdminRequiredMixin, DeleteView):
    model = Movie
    success_url = reverse_lazy("movies:movie")
    template_name = 'movies/confirmation.html'
    # queryset = Movie.objects.all()

class MovieDetailView(TemplateView):
    template_name = 'movies/movieDetail.html'

    def get(self, request, movie_id, *args, **kwargs):
        movie = get_object_or_404(Movie, id=movie_id)
        cast = MovieCast.objects.filter(movie_name=movie)
        languages = MovieLanguage.objects.filter(movie_name=movie)
        # reviews = movie.reviews.all()  # uses related_name in Review model
        context = {
            'movie': movie,
            'cast': cast,
            'languages': languages,
            # 'reviews': reviews,
        }
        return render(request, self.template_name, context)

#People #peoplepageview
# class PersonListView(LoginRequiredMixin, AdminRequiredMixin, ListView):
class PersonListView(UserAccessMixin, ListView):
    model = Person
    template_name = 'movies/people.html'
    context_object_name = 'people'

    def get_queryset(self):
        queryset = super().get_queryset()
        print(f"Initial queryset count: {queryset.count()}") ##

        role_type = self.request.GET.get('role_type')
        search_query = self.request.GET.get('search_person')

        print(f"role_type: {role_type}") ## 
        print(f"search_query: {search_query}") ##

        if role_type and role_type != "all":
            queryset = queryset.filter(role_type=role_type)
            print(f"Filtered by role_type. New count: {queryset.count()}") ##
        # else:
        #     queryset = Person.objects.all()
        #     print(f"Display all role type. count: {queryset.count()}") #3

        if search_query:
            queryset = queryset.filter(person_name__icontains=search_query)
            print(f"Filtered by search_query. New count: {queryset.count()}") ##

        print(f"Final queryset count: {queryset.count()}") ##

        return queryset#.order_by('person_name')
    
class DeletePeople(LoginRequiredMixin, AdminRequiredMixin, DeleteView):
    model = Person
    success_url = reverse_lazy("movies:people")
    template_name = 'movies/confirmation.html'

class PersonDetailView(TemplateView):
    template_name = 'movies/personDetail.html'
    

MovieManagementSystem/MovieManagement/moviemanagement/movies/templates/movies/addgenre.html
{% extends 'movies/base.html' %}
{% block title %}10.Add Genre Page{% endblock %}

{% block content %}
<div class="add-genre-container">
    <div></div>
    <h1>{% if genre %}Edit Genre{% else %}Add New Genre{% endif %}</h1>
    <div>
        {% if genre %}
        <form action="{% url 'movies:editgenre' genre_id=genre.id %}" method="post">
        {% else %}
        <form action="{% url 'movies:addgenre' %}" method="post">
        {% endif %}
        
        {% csrf_token %}
            <div>
                <label for="genre-name">Genre Name</label>
                <input type="text" name="genre_name" id="genre-name" placeholder="e.g. Action, Comedy, Drama" value="{{ genre.genre_name|default:'' }}" required/>
            </div>
            <div class="btn">
                <button type="submit">{% if genre %}Update Genre{% else %}Save Genre{% endif %}</button>
                <button type="button"><a href="{% url 'movies:genre' %}">Cancel</a></button>
            </div>
        </form>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
{% endblock content %}

MovieManagementSystem/MovieManagement/moviemanagement/movies/templates/movies/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Movie Management{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'movies/css/style.css' %}">
</head>

<body>
    <!-- whole-page -->
    <div class="whole-container">

        <div class="navbar">
            <div><h3>Movie Management System</h3></div>
            <div class="navbar-navitems">
                <div class="nav-item">
                    <a class="nav-link" href="{% url 'movies:home' %}">Home</a>
                </div>
                <div class="nav-item">
                    <a class="nav-link" href="{% url 'movies:movie' %}">Movies</a>
                </div>
                <div class="nav-item">
                    <a class="nav-link" href="{% url 'movies:genre' %}">Genre</a>
                </div>
                <div class="nav-item">
                    <a class="nav-link" href="{% url 'movies:people' %}">People</a>
                </div>
                {% if user.user_role == 'admin' %}
                    <div class="nav-item">
                        <a class="nav-link" href="{% url 'movies:addmovie' %}">Add Movie</a>
                    </div>
                {% endif %}
                <a class="nav-link" href="{% url 'movies:signout' %}">LogOut</a>
            </div>
            {% comment %} <div class="account-menu"> {% endcomment %}
                {% comment %} <button type="button" class="account-button"> {% endcomment %}
                    {% comment %} <a class="nav-link" href="{% url 'movies:signout' %}">SignOut</a> {% endcomment %}
                {% comment %} </button> {% endcomment %}
                {% comment %} <ul class="menu-options">
                    <li><a href="#">Profile</a></li>
                    <li><a href="#">Theme</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'movies:signout' %}">SignOut</a></li>
                </ul> {% endcomment %}
            {% comment %} </div> {% endcomment %}
        </div>

        <!-- Toast container -->
        <div id="toast-container"></div>

        <main>
            <!-- Page content -->
            <div class="main-content">
                {% block content %}
                <br><br><br>
                {% endblock %}
            </div>
        </main>        
    </div>


    <script>
        function showToast(message, duration = 3000) {
            const toastContainer = document.getElementById("toast-container");
            if (!toastContainer) return;

            const toast = document.createElement("div");
            toast.classList.add("toast");
            toast.innerText = message;
            toastContainer.appendChild(toast);
            
            setTimeout(() => {
                toast.classList.add("show");
            }, 10);

            setTimeout(() => {
                toast.classList.remove("show");
                setTimeout(() => {
                    toast.remove();
                }, 500);
            }, duration);
        }

        {% if messages %}
            {% for message in messages %}
                showToast("{{ message|escapejs }}");
            {% endfor %}
        {% endif %}
    </script>
</body>
</html>

MovieManagementSystem/MovieManagement/moviemanagement/movies/templates/movies/movieDetail.html
{% extends 'movies/base.html' %}
{% block title %}3. Movie Detail Page{% endblock %}

{% block content %}
<div class="movie-detail-container">
    
    <div class="movie-detail-upper-block">
        <!-- Movie Header Section -->
        <div class="movie-detail">
            <div class="movie-poster">
                {% if movie.poster %}
                    <img src="{{ movie.poster.url }}" alt="{{ movie.title }}">
                {% else %}
                    <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 1026 1024"><path fill="#000000" d="M969.057 248h-1l-71-119l-127 17l80 120l-212 33l-81-120l-116 18l81 120l-220 35l-77-127l-122 24l81 121l-95 15h104l-64 127h128l64-127h192l-64 127h128l64-127h192l-64 127h128l64-127q26 0 45 18.5t19 44.5v512q0 27-19 45.5t-45 18.5h-895q-27 0-45.5-18.5T2.057 960V448q0-26 18.5-44.5t45.5-18.5q-5-2-12-5.5t-20.5-17.5t-16.5-31l-16-124q-3-25 13.5-45.5t42.5-23.5l882-137q26-3 46.5 13t23.5 41l16 124q3 25-13.5 45.5t-42.5 23.5zm-808 648h704q13 0 22.5-9.5t9.5-22.5t-9.5-22.5t-22.5-9.5h-704q-13 0-22.5 9.5t-9.5 22.5t9.5 22.5t22.5 9.5zm0-192h704q13 0 22.5-9t9.5-22.5t-9.5-23t-22.5-9.5h-704q-13 0-22.5 9.5t-9.5 23t9.5 22.5t22.5 9z"/></svg>
                {% endif %}
            </div>
            <div class="movie-main">
                <h1>{{ movie.title }}</h1>
                <p>{{ movie.tagline|default:"" }}</p>

                <table>
                    <thead>
                        <tr>
                            <th>Genre</th>
                            <th>Release Year</th>
                            <th>Duration</th>
                            <th>Director</th>
                        </tr>
                    </thead>
                    <tbody> 
                        <tr>
                            <td>{{ movie.genre.genre_name }}</td>
                            <td>{{ movie.release_year }}</td>
                            <td>{{ movie.duration }} min</td>
                            <td>{{ movie.director.person_name }}</td>
                        </tr>
                    </tbody>
                </table>

                {% comment %} <h2><span>⭐ {{ movie.average_rating|default:"No Rating" }}</span></h2><br> {% endcomment %}
                <div class="movie-info">
                    {% comment %} <h2> {% endcomment %}
                    <span>
                        <p> ⭐ {{ movie.rating }}/10</p>
                        <div class="stars">
                        {% for i in "12345678910" %}
                            {% if forloop.counter <= movie.rating|floatformat:0 %}
                            ⭐                        
                            {% endif %}
                        {% endfor %}
                        </div>
                    </span>
                {% comment %} </h2> {% endcomment %}
                </div><br>

                <div class="movie-actions">
                    {% if user.user_role == 'admin' %}
                        <button type="button"><a href="{% url 'movies:editmovie' movie.id %}">Edit Movie</a></button>
                        <button type="button"><a href="{% url 'movies:deletemovie' pk=movie.id %}">Delete Movie</a></button>
                    {% endif %}
                    <button type="button"><a href="{% url 'movies:movie' %}">Back to List</a></button>
                </div>
            </div>
        </div>

        <!-- Overview Section -->
        <div class="movie-description">
            <h2 class="block-title">Overview</h2>
            <p>{{ movie.description|default:"No description available." }}</p>
        </div>

        <!-- Language Section -->
        <div class="movie-language">
            <h2 class="block-title">Languages</h2>
            {% if languages %}
            <div class="lang-list">
                {% for movie_lang in languages %}
                    <div>{{ movie_lang.language.language }}</div>
                {% endfor %}
            </div>
            {% else %}
            <p>No languages have been added yet.</p>
            {% endif %}
        </div>

        <!-- Cast Section -->
        <div class="movie-cast">
            <h2 class="block-title">Cast</h2>
            {% if cast %}
                <div class="cast-list">
                    {% for cast_member in cast %}
                        <div></h3>{{ cast_member.person.person_name }}</h3><br> as {{ cast_member.character_name }}</div>
                    {% endfor %}
                </div>
            {% else %}
                <p>No cast members have been added yet.</p>
            {% endif %}
        </div>
    </div>

    <!-- Review Section -->
    <div class="review-container">
        <h2 class="block-title">User Reviews</h2>
        <button><a href="{% url 'movies:addreview' movie.id %}">+ Add Your Review</a></button>
        <br><br>

        {% for review in movie.reviews.all %}
        <div class="single-review">
            <div>
                <h3>
                    {% if review.user_name %}
                        {{ review.user_name.username }}
                    {% else %}
                        Anonymous User
                    {% endif %}
                </h3>
                <p><strong>Rating:</strong> {{ review.rating }}/10</p>
                <p><em>{{ review.comment }}</em></p>
                <p><small>{{ review.created_at }}</small><p>
            </div>
            {% if request.user == review.user_name %}
            <div>
                <button type="button"><a href="{% url 'movies:editreview' movie.id review.id %}">Edit</a></button>
                <form action="{% url 'movies:deletereview' review.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Delete</button>
                </form>
            </div>
            {% endif %}
        </div>
        {% empty %}
        <p>No reviews yet.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

MovieManagementSystem/MovieManagement/moviemanagement/movies/templates/movies/people.html
{% extends 'movies/base.html' %}

{% block title %}6.People (Actor/Director) {% endblock %}

{% block content %}
<div class="people-container">
    <div class="people-header">
        <h1>All People</h1>
        {% if user.user_role == 'admin' %}
        <a class="nav-link" href="{% url 'movies:addpeople' %}"><button>+ Add New Person</button></a>
        {% endif %}
    </div>
    <br>

    <div class="filter-container">
        <form class="filter-person" method="get" action="{% url 'movies:people' %}" role="search">
            <div class="filter-grp">
                <label for="role_type">Role Type</label>
                {% comment %} <select id="role_type" name="role_type">
                    {% for value, label in person.role_type.choices %}
                        <option value="{{ value }}">{{ label }}</option>
                    {% endfor %}
                </select> {% endcomment %}
                <select class="form-select" name="role_type">
                    <option value="all">All Roles</option>
                    <option value="actor">Actor</option>
                    <option value="director">Director</option>
                    <option value="writer">Writer</option>
                </select>
            </div>
            <div class="filter-grp">
                <label for="search_person">Search</label>
                <input type="search" name="search_person" value="{{ request.GET.search_person|default:'' }}" placeholder="Search by name..."/>
            </div>
            <button class="filter-grp" type="submit">Apply Filters</button>
        </form>
    </div>

    <div class="people-section">
    {% for person in people %}
    {% comment %} </a class="nav-link" href="{% url 'movies:personDetail' person.id %}"> {% endcomment %}
    {% comment %} <a class="nav-link" href="{% url 'movies:personDetail' person.id %}"> {% endcomment %}
        <div class="person-card">
            <div class="person-profile">
                {% if person.profile_photo %}
                    <img src="{{ person.profile_photo.url }}" alt="{{ person.person_name }}">
                {% else %}
                    {% comment %} 👤 {% endcomment %}
                    <svg xmlns="http://www.w3.org/2000/svg" width="70" height="70" viewBox="0 0 512 512"><path fill="#3973b1" d="M332.64 64.58C313.18 43.57 286 32 256 32c-30.16 0-57.43 11.5-76.8 32.38c-19.58 21.11-29.12 49.8-26.88 80.78C156.76 206.28 203.27 256 256 256s99.16-49.71 103.67-110.82c2.27-30.7-7.33-59.33-27.03-80.6M432 480H80a31 31 0 0 1-24.2-11.13c-6.5-7.77-9.12-18.38-7.18-29.11C57.06 392.94 83.4 353.61 124.8 326c36.78-24.51 83.37-38 131.2-38s94.42 13.5 131.2 38c41.4 27.6 67.74 66.93 76.18 113.75c1.94 10.73-.68 21.34-7.18 29.11A31 31 0 0 1 432 480"/></svg>
                {% endif %}
            </div>
            <div class="person-info">
                <h3>{{ person.person_name }}</h3>
                <span>{{ person.role_type }}</span>
                <p>Born: {{ person.birth_date }}</p>
                <p>{{ person.moviecast_set.count }} movies acted <br> {{ person.directed_movies.count }} movies directed</p>
                {% comment %} <p>{% if acted_movie_casts %} {{ person.moviecast_set.count }} movies acted {% else %} {{ person.directed_movies.count }} movies directed{% endif %}</p> {% endcomment %}
            </div>
            <div class="action-btn">
                <a href="{% url 'movies:personDetail' person.id %}"><button>View</button></a>
                {% if user.user_role == 'admin' %}
                    <a href="{% url 'movies:editpeople' person.id %}"><button>Edit</button></a>
                    <a href="{% url 'movies:deletepeople' pk=person.id %}"><button>Delete</button></a>
                {% endif %}
            </div>
        </div>
    {% comment %} </a> {% endcomment %}
    {% empty %}
        <p>No person found.</p>
    {% endfor %}
    </div>
</div>
{% endblock content %}